on:
  push:
  pull_request:
  workflow_dispatch:  # 支持手动触发

name: Auto Build & Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate debug keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          mkdir -p ~/.android/
          mv debug.keystore ~/.android/

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Prepare release info
        id: release_info
        run: |
          # 确定APK名称、标签和描述
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "apk_name=Gotify-debug-manual-${{ github.sha }}.apk" >> $GITHUB_OUTPUT
            echo "tag_name=manual-build-${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "description=Manual debug build" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "apk_name=Gotify-debug-${{ github.ref_name }}.apk" >> $GITHUB_OUTPUT
            echo "tag_name=${{ github.ref }}" >> $GITHUB_OUTPUT
            echo "description=Tagged debug build" >> $GITHUB_OUTPUT
          else
            echo "apk_name=Gotify-debug-${{ github.sha }}.apk" >> $GITHUB_OUTPUT
            echo "tag_name=debug-build-${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "description=Auto debug build" >> $GITHUB_OUTPUT
          fi
          # 复制APK文件
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ steps.release_info.outputs.apk_name }}

      - name: Upload to Releases
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          overwrite: true
          file: app/build/outputs/apk/debug/${{ steps.release_info.outputs.apk_name }}
          asset_name: ${{ steps.release_info.outputs.apk_name }}
          body: ${{ steps.release_info.outputs.description }}
