on: [push, pull_request]

name: Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew build --stacktrace
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          # 使用调试模式构建，不需要签名配置
          ./gradlew assembleDebug --stacktrace
          # 调试版本通常输出在debug目录下
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Gotify-debug.apk
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 更新为调试版本的APK路径
          file: app/build/outputs/apk/debug/Gotify-debug.apk
          tag: ${{ github.ref }}
          overwrite: true