on:
  push:
  pull_request:
  workflow_dispatch:  # 支持手动触发

name: Auto Build & Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate debug keystore
        run: |
          # 自动生成Android调试密钥
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          # 将生成的密钥库移动到项目目录
          mkdir -p ~/.android/
          mv debug.keystore ~/.android/

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Prepare APK for release
        id: prepare_apk
        run: |
          # 根据触发方式命名APK
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            APK_NAME="Gotify-debug-manual-${{ github.sha }}.apk"
            TAG_NAME="manual-build-${{ github.sha }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            APK_NAME="Gotify-debug-${{ github.ref_name }}.apk"
            TAG_NAME="${{ github.ref }}"
          else
            APK_NAME="Gotify-debug-${{ github.sha }}.apk"
            TAG_NAME="debug-build-${{ github.sha }}"
          fi
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/$APK_NAME
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Upload to Releases (manual trigger or tag)
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.prepare_apk.outputs.tag_name }}
          overwrite: true
          file: app/build/outputs/apk/debug/${{ steps.prepare_apk.outputs.apk_name }}
          asset_name: ${{ steps.prepare_apk.outputs.apk_name }}
          body: ${{ github.event_name == 'workflow_dispatch' ? 'Manual debug build' : 'Auto-generated debug build' }}
