on: [push, pull_request]

name: Build

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      # 生成调试签名密钥
      - name: Generate debug keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      # 构建项目，不区分是否为tag
      - name: Build project
        run: ./gradlew build --stacktrace
        env:
          # 使用调试签名配置
          ANDROID_DEBUG_KEYSTORE: ${{ github.workspace }}/debug.keystore
          ANDROID_DEBUG_STORE_PASSWORD: android
          ANDROID_DEBUG_KEY_ALIAS: androiddebugkey
          ANDROID_DEBUG_KEY_PASSWORD: android

      # 仅在tag推送时发布APK
      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        name: Prepare release APK
        run: |
          # 复制并命名APK
          cp app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/Gotify.apk

      - if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/release/Gotify.apk
          tag: ${{ github.ref }}
          overwrite: true
