on:
  push:
  pull_request:
  workflow_dispatch:  # 支持手动触发

name: Auto Build & Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate debug keystore
        run: |
          # 自动生成Android调试密钥（无需手动配置）
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
          # 将生成的密钥库移动到项目目录
          mkdir -p ~/.android/
          mv debug.keystore ~/.android/

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Prepare APK for release
        run: |
          # 根据触发方式命名APK
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Gotify-debug-manual-${{ github.sha }}.apk
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Gotify-debug-${{ github.ref_name }}.apk
          else
            cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Gotify-debug-${{ github.sha }}.apk
          fi

      - name: Upload to Releases (manual trigger or tag)
        if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # 无需手动配置，GitHub自动提供
          # 生成发布标签
          tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref || 'debug-build-' }}${{ github.sha }}
          overwrite: true
          # 选择要上传的APK
          file: ${{
            github.event_name == 'workflow_dispatch' ?
            'app/build/outputs/apk/debug/Gotify-debug-manual-${{ github.sha }}.apk' :
            (startsWith(github.ref, 'refs/tags/') ?
            'app/build/outputs/apk/debug/Gotify-debug-${{ github.ref_name }}.apk' :
            'app/build/outputs/apk/debug/Gotify-debug-${{ github.sha }}.apk')
        }}
          asset_name: ${{
            github.event_name == 'workflow_dispatch' ?
            'Gotify-debug-manual-${{ github.sha }}.apk' :
            (startsWith(github.ref, 'refs/tags/') ?
            'Gotify-debug-${{ github.ref_name }}.apk' :
            'Gotify-debug-${{ github.sha }}.apk')
        }}
          body: ${{ github.event_name == 'workflow_dispatch' ? 'Manual debug build' : 'Auto-generated debug build' }}